### ISSUE TITLE
Two undefined names: 'ResNet18' and 'idx'

### ISSUE THREAD

**Issue by cclauss** [andreasveit/convnet-aig#3]
[flake8](http://flake8.pycqa.org) testing of https://github.com/andreasveit/convnet-aig on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./convnet_aig.py:337:11: F821 undefined name 'ResNet18'
    net = ResNet18()
          ^
./gumbelmodule.py:64:24: F821 undefined name 'idx'
                return idx
                       ^
2     F821 undefined name 'ResNet18'
2
```

**Comment by andreasveit** [comment]
Thanks for running the test. I removed these deprecated artifacts.
