### ISSUE TITLE
Is the gumbel softmax still needed in test phrase?

### ISSUE THREAD

**Issue by ToTheBeginning** [andreasveit/convnet-aig#5]
Is it ok to directly use argmax rather than gumbel softmax?

**Comment by Vincent-Hoo** [comment]
The gumbel softmax module seems to be inconsistent with that in the paper. Can anybody explain why the implementation is like that?

**Comment by ToTheBeginning** [comment]
The author tell me that it should probably be fine to make that deterministic in the test phrase.
Beacuse my environment is not match with the environment required by the code, so I will not test by myself.
