### ISSUE TITLE
backward use argmax?

### ISSUE THREAD

**Issue by licheng1995** [andreasveit/convnet-aig#8]
hello, I read the code. In the backward, force-hard is stiil true, which is different in paper.

**Comment by andreasveit** [comment]
As you can see here:
https://github.com/andreasveit/convnet-aig/blob/47633cd463f4ac92f05152d825b601f1e8bf09fe/gumbelmodule.py#L62 
the backwards pass is always via the softmax sample created here:
https://github.com/andreasveit/convnet-aig/blob/master/gumbelmodule.py#L58
whether you use hard or soft samples in the forward pass.
